CREATE TABLE email_messages (
    message_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    sender_user_id BIGINT UNSIGNED NOT NULL,
    thread_key CHAR(36) NOT NULL,
    parent_message_id BIGINT UNSIGNED NULL,
    subject VARCHAR(255) NOT NULL DEFAULT '',
    body LONGTEXT NOT NULL,
    status VARCHAR(20) NOT NULL,
    sent_at DATETIME(6) NULL,
    version BIGINT NOT NULL DEFAULT 0,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    created_by BIGINT UNSIGNED NULL,
    updated_by BIGINT UNSIGNED NULL,
    PRIMARY KEY (message_id),
    KEY idx_email_messages_sender_status (sender_user_id, status),
    KEY idx_email_messages_thread_sent (thread_key, sent_at),
    KEY idx_email_messages_sent_at (sent_at),
    CONSTRAINT fk_email_messages_sender FOREIGN KEY (sender_user_id) REFERENCES users(user_id),
    CONSTRAINT fk_email_messages_parent FOREIGN KEY (parent_message_id) REFERENCES email_messages(message_id),
    CONSTRAINT ck_email_messages_status CHECK (status IN ('DRAFT', 'SENT'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE email_recipients (
    recipient_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    message_id BIGINT UNSIGNED NOT NULL,
    recipient_user_id BIGINT UNSIGNED NULL,
    email_address VARCHAR(254) NOT NULL,
    recipient_type VARCHAR(10) NOT NULL,
    delivery_status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    delivered_at DATETIME(6) NULL,
    failure_reason VARCHAR(500) NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    created_by BIGINT UNSIGNED NULL,
    updated_by BIGINT UNSIGNED NULL,
    PRIMARY KEY (recipient_id),
    UNIQUE KEY uq_email_recipient_message_address (message_id, email_address),
    KEY idx_email_recipients_user_message (recipient_user_id, message_id),
    KEY idx_email_recipients_message_type (message_id, recipient_type),
    CONSTRAINT fk_email_recipients_message FOREIGN KEY (message_id) REFERENCES email_messages(message_id) ON DELETE CASCADE,
    CONSTRAINT fk_email_recipients_user FOREIGN KEY (recipient_user_id) REFERENCES users(user_id),
    CONSTRAINT ck_email_recipients_type CHECK (recipient_type IN ('TO', 'CC', 'BCC')),
    CONSTRAINT ck_email_recipients_delivery CHECK (delivery_status IN ('PENDING', 'DELIVERED', 'FAILED'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE email_mailbox_entries (
    message_id BIGINT UNSIGNED NOT NULL,
    user_id BIGINT UNSIGNED NOT NULL,
    mailbox_role VARCHAR(20) NOT NULL,
    is_read BOOLEAN NOT NULL DEFAULT FALSE,
    is_starred BOOLEAN NOT NULL DEFAULT FALSE,
    is_important BOOLEAN NOT NULL DEFAULT FALSE,
    is_archived BOOLEAN NOT NULL DEFAULT FALSE,
    is_spam BOOLEAN NOT NULL DEFAULT FALSE,
    trashed_at DATETIME(6) NULL,
    version BIGINT NOT NULL DEFAULT 0,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    created_by BIGINT UNSIGNED NULL,
    updated_by BIGINT UNSIGNED NULL,
    PRIMARY KEY (message_id, user_id),
    KEY idx_email_mailbox_user_trash (user_id, trashed_at),
    KEY idx_email_mailbox_user_flags (user_id, is_read, is_starred, is_important),
    KEY idx_email_mailbox_user_role (user_id, mailbox_role),
    CONSTRAINT fk_email_mailbox_message FOREIGN KEY (message_id) REFERENCES email_messages(message_id) ON DELETE CASCADE,
    CONSTRAINT fk_email_mailbox_user FOREIGN KEY (user_id) REFERENCES users(user_id),
    CONSTRAINT ck_email_mailbox_role CHECK (mailbox_role IN ('SENDER', 'RECIPIENT'))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE email_attachments (
    attachment_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    message_id BIGINT UNSIGNED NOT NULL,
    uploaded_by_user_id BIGINT UNSIGNED NOT NULL,
    original_filename VARCHAR(255) NOT NULL,
    stored_filename VARCHAR(255) NOT NULL,
    content_type VARCHAR(150) NOT NULL,
    file_size BIGINT NOT NULL,
    storage_path VARCHAR(1024) NOT NULL,
    created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
    updated_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
    created_by BIGINT UNSIGNED NULL,
    updated_by BIGINT UNSIGNED NULL,
    PRIMARY KEY (attachment_id),
    UNIQUE KEY uq_email_attachments_stored_filename (stored_filename),
    KEY idx_email_attachments_message (message_id),
    CONSTRAINT fk_email_attachments_message FOREIGN KEY (message_id) REFERENCES email_messages(message_id) ON DELETE CASCADE,
    CONSTRAINT fk_email_attachments_uploader FOREIGN KEY (uploaded_by_user_id) REFERENCES users(user_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
