spring.application.name=trafficsourceapi

spring.datasource.url=jdbc:mysql://localhost:3306/crm_dashboard_demo
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.open-in-view=false

# user override (development-only)
chat.dev-user-override-enabled=true
chat.default-dev-user-id=1

# Chat attachment upload limits
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.jpa.properties.hibernate.jdbc.time_zone=UTC