package com.example.Call.DTO.Request;

import com.fasterxml.jackson.annotation.JsonProperty;

import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Size;

public record CreateCallRequest(

        /*
         * Generated by communication.js using crypto.randomUUID().
         */
        @JsonProperty("callId")
        @NotBlank
        @Pattern(
            regexp =
                "^[0-9a-fA-F]{8}-" +
                "[0-9a-fA-F]{4}-" +
                "[1-5][0-9a-fA-F]{3}-" +
                "[89abAB][0-9a-fA-F]{3}-" +
                "[0-9a-fA-F]{12}$",
            message = "callId must be a valid UUID."
        )
        String callId,

        /*
         * Retains the original communication.js field.
         * The backend will resolve this email to an existing User.
         */
        @JsonProperty("to")
        @NotBlank
        @Email
        @Size(max = 150)
        String recipientEmail,

        @JsonProperty("type")
        @NotBlank
        @Pattern(
            regexp = "(?i)audio|video",
            message = "type must be audio or video."
        )
        String type
) {
}
