package com.example.LeadImport.Service;

import com.example.CRM.Entity.*;
import com.example.CRM.Repository.*;
import com.example.Common.DTO.Response.PageResponse;
import com.example.Common.Exception.*;
import com.example.Common.Service.CurrentUserService;
import com.example.LeadImport.DTO.*;
import com.example.LeadImport.Entity.*;
import com.example.LeadImport.Parser.*;
import com.example.LeadImport.Repository.*;
import tools.jackson.core.type.TypeReference;
import tools.jackson.databind.ObjectMapper;
import lombok.RequiredArgsConstructor;
import org.springframework.data.domain.*;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.multipart.MultipartFile;
import java.math.BigDecimal;
import java.nio.charset.StandardCharsets;
import java.security.MessageDigest;
import java.time.LocalDateTime;
import java.util.*;
import java.util.regex.Pattern;

@Service @RequiredArgsConstructor
public class LeadImportService {
 private static final long MAX_FILE_SIZE=10L*1024*1024; private static final int MAX_ROWS=10000; private static final int MAX_PAGE=100;
 private static final Set<String> FIELDS=Set.of("leadName","firstName","lastName","email","phone","source","geoLocation","state","interestedService","personalDetails","externalId","estimatedValue");
 private static final Pattern EMAIL=Pattern.compile("^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$");
 private final LeadImportRepository imports; private final LeadImportRowRepository rows; private final LeadRepository leads; private final LeadHistoryRepository history; private final LeadSourceRepository sources; private final UserRepository users; private final CurrentUserService currentUserService; private final List<LeadFileParser> parsers; private final ObjectMapper json;

 @Transactional
 public LeadImportResponse upload(MultipartFile file){User actor=actor();requireImporter(actor);if(file==null||file.isEmpty())throw new IllegalArgumentException("Choose a non-empty CSV, Excel or JSON file.");if(file.getSize()>MAX_FILE_SIZE)throw new IllegalArgumentException("The maximum import file size is 10 MB.");LeadImportFileType type=type(file.getOriginalFilename());LeadFileParser parser=parsers.stream().filter(p->p.supports(type)).findFirst().orElseThrow(()->new IllegalArgumentException("Unsupported import format."));try{ParsedLeadFile parsed=parser.parse(file);if(parsed.columns().isEmpty())throw new IllegalArgumentException("The file does not contain column headers.");if(parsed.rows().isEmpty())throw new IllegalArgumentException("The file does not contain lead rows.");if(parsed.rows().size()>MAX_ROWS)throw new IllegalArgumentException("An import can contain at most 10,000 rows.");LeadImport job=new LeadImport();job.setFileName(safeName(file.getOriginalFilename()));job.setFileType(type);job.setStatus(LeadImportStatus.UPLOADED);job.setUploadedBy(actor);job.setDetectedColumnsJson(write(parsed.columns()));job.setTotalRecords(parsed.rows().size());job=imports.save(job);List<LeadImportRow> staged=new ArrayList<>();int number=2;for(Map<String,String> raw:parsed.rows()){LeadImportRow row=new LeadImportRow();row.setLeadImport(job);row.setRowNumber(number++);row.setRawDataJson(write(raw));staged.add(row);}rows.saveAll(staged);return response(job);}catch(IllegalArgumentException e){throw e;}catch(Exception e){throw new IllegalArgumentException("Unable to read the uploaded file: "+e.getMessage());}}

 @Transactional
 public LeadImportResponse saveMapping(Long id,Map<String,String> mapping){User actor=actor();LeadImport job=owned(id,actor);ensureEditable(job);Map<String,String> clean=new LinkedHashMap<>();mapping.forEach((field,column)->{if(!FIELDS.contains(field))throw new IllegalArgumentException("Unknown CRM field: "+field);if(column!=null&&!column.isBlank())clean.put(field,column.trim());});if(clean.values().stream().distinct().count()!=clean.size())throw new IllegalArgumentException("An uploaded column cannot be mapped more than once.");if(!clean.containsKey("leadName")&&!clean.containsKey("firstName")&&!clean.containsKey("lastName"))throw new IllegalArgumentException("Map Lead Name, First Name or Last Name.");job.setColumnMappingJson(write(clean));job.setStatus(LeadImportStatus.MAPPED);return response(imports.save(job));}

 @Transactional
 public LeadImportResponse validate(Long id){User actor=actor();LeadImport job=owned(id,actor);if(job.getColumnMappingJson()==null)throw new ConflictException("MAPPING_REQUIRED","Save column mapping before validation.");Map<String,String> mapping=map(job.getColumnMappingJson());Set<String> batchEmails=new HashSet<>(),batchPhones=new HashSet<>();int valid=0,invalid=0,duplicates=0;List<LeadImportRow> staged=rows.findByLeadImportImportIdOrderByRowNumber(id);for(LeadImportRow row:staged){Map<String,String> raw=map(row.getRawDataJson());Map<String,String> normalized=normalize(raw,mapping);List<String> errors=validateRow(normalized);String hash=hash(normalized),email=trim(normalized.get("email")).toLowerCase(Locale.ROOT),phone=trim(normalized.get("phone"));boolean duplicateEmail=!email.isBlank()&&!batchEmails.add(email);boolean duplicatePhone=!phone.isBlank()&&!batchPhones.add(phone);boolean databaseEmail=!email.isBlank()&&leads.existsByEmailIgnoreCase(email);boolean databasePhone=!phone.isBlank()&&leads.existsByPhone(phone);boolean storedDuplicate=!hash.isBlank()&&leads.existsByDuplicateHash(hash);if(duplicateEmail)errors.add("Duplicate email address in this file.");else if(databaseEmail||storedDuplicate)errors.add("Email address already exists in CRM.");if(duplicatePhone)errors.add("Duplicate phone number in this file.");else if(databasePhone)errors.add("Phone number already exists in CRM.");boolean duplicate=duplicateEmail||duplicatePhone||databaseEmail||databasePhone||storedDuplicate;row.setNormalizedDataJson(write(normalized));row.setValidationErrorsJson(write(errors));row.setDuplicateRow(duplicate);row.setValidRow(errors.isEmpty()&&!duplicate);if(duplicate)duplicates++;else if(errors.isEmpty())valid++;else invalid++;}rows.saveAll(staged);job.setValidRecords(valid);job.setInvalidRecords(invalid);job.setDuplicateRecords(duplicates);job.setStatus(LeadImportStatus.VALIDATED);return response(imports.save(job));}

 @Transactional(readOnly=true)
 public PageResponse<LeadImportResponse> list(int page,int size){User actor=actor();requireImporter(actor);Pageable p=PageRequest.of(Math.max(0,page),Math.min(MAX_PAGE,Math.max(1,size)),Sort.by(Sort.Direction.DESC,"createdAt"));Page<LeadImport> result=actor.getRole()==UserRole.ADMIN?imports.findAllByOrderByCreatedAtDesc(p):imports.findVisibleToManager(actor.getUserId(),p);return new PageResponse<>(result.map(this::response).getContent(),result.getNumber(),result.getSize(),result.getTotalElements(),result.getTotalPages(),result.hasNext());}
 @Transactional(readOnly=true) public LeadImportResponse get(Long id){return response(owned(id,actor()));}
 @Transactional(readOnly=true) public PageResponse<LeadImportRowResponse> preview(Long id,int page,int size){User actor=actor();owned(id,actor);Page<LeadImportRow> result=rows.findByLeadImportImportIdOrderByRowNumber(id,PageRequest.of(Math.max(0,page),Math.min(MAX_PAGE,Math.max(1,size))));return new PageResponse<>(result.map(this::rowResponse).getContent(),result.getNumber(),result.getSize(),result.getTotalElements(),result.getTotalPages(),result.hasNext());}

 @Transactional public LeadImportResponse updateRow(Long id,Long rowId,Map<String,String> values){User actor=actor();LeadImport job=owned(id,actor);ensureEditable(job);LeadImportRow row=rows.findByRowIdAndLeadImportImportId(rowId,id).orElseThrow(()->new ResourceNotFoundException("Import row was not found."));if(row.getImportedLead()!=null)throw new ConflictException("ROW_ALREADY_IMPORTED","An imported row cannot be edited.");List<String> columns=list(job.getDetectedColumnsJson());Map<String,String> clean=new LinkedHashMap<>();for(String column:columns)clean.put(column,trim(values.get(column)));row.setRawDataJson(write(clean));rows.saveAndFlush(row);return validate(id);}
 @Transactional public LeadImportResponse deleteRow(Long id,Long rowId){User actor=actor();LeadImport job=owned(id,actor);ensureEditable(job);LeadImportRow row=rows.findByRowIdAndLeadImportImportId(rowId,id).orElseThrow(()->new ResourceNotFoundException("Import row was not found."));if(row.getImportedLead()!=null)throw new ConflictException("ROW_ALREADY_IMPORTED","An imported row cannot be deleted.");rows.delete(row);rows.flush();job.setTotalRecords(Math.max(0,job.getTotalRecords()-1));imports.save(job);return job.getColumnMappingJson()==null?response(job):validate(id);}
 @Transactional(readOnly=true) public LeadImportProgressResponse progress(Long id){User actor=actor();LeadImport job=trackable(id,actor);boolean teamOnly=actor.getRole()==UserRole.MANAGER&&!job.getUploadedBy().getUserId().equals(actor.getUserId());List<LeadImportRow> imported=teamOnly?rows.findVisibleToManager(id,actor.getUserId()):rows.findByLeadImportImportIdAndImportedLeadIsNotNullOrderByRowNumber(id);Map<LeadStatus,Long> totals=emptyStatusCounts();Map<Long,Map<LeadStatus,Long>> byAssignee=new LinkedHashMap<>();Map<Long,String> assigneeNames=new LinkedHashMap<>();List<LeadImportProgressLeadResponse> leadItems=new ArrayList<>();for(LeadImportRow row:imported){Lead lead=row.getImportedLead();LeadStatus status=lead.getStatus();totals.put(status,totals.get(status)+1);User assignee=lead.getAssignedUser();Long assigneeId=assignee==null?0L:assignee.getUserId();String assigneeName=assignee==null?"Pending distribution":assignee.getFullName();assigneeNames.put(assigneeId,assigneeName);Map<LeadStatus,Long> counts=byAssignee.computeIfAbsent(assigneeId,key->emptyStatusCounts());counts.put(status,counts.get(status)+1);leadItems.add(new LeadImportProgressLeadResponse(lead.getLeadId(),lead.getLeadName(),lead.getEmail(),status,assignee==null?null:assigneeId,assigneeName,lead.getUpdatedAt()));}List<LeadImportAssigneeProgressResponse> assigneeItems=new ArrayList<>();byAssignee.forEach((assigneeId,counts)->assigneeItems.add(new LeadImportAssigneeProgressResponse(assigneeId==0L?null:assigneeId,assigneeNames.get(assigneeId),counts.values().stream().mapToLong(Long::longValue).sum(),counts)));return new LeadImportProgressResponse(id,job.getFileName(),imported.size(),totals,assigneeItems,leadItems);}

 @Transactional
 public LeadImportResponse execute(Long id,List<Long> executiveIds){User actor=actor();LeadImport job=owned(id,actor);if(job.getStatus()!=LeadImportStatus.VALIDATED)throw new ConflictException("VALIDATION_REQUIRED","Validate the import before execution.");List<User> executives=executiveIds.stream().distinct().map(uid->users.findById(uid).orElseThrow(()->new ResourceNotFoundException("A selected Sales Executive was not found."))).toList();executives.forEach(u->validateExecutive(actor,u));List<LeadImportRow> validRows=rows.findByLeadImportImportIdOrderByRowNumber(id).stream().filter(LeadImportRow::isValidRow).filter(r->r.getImportedLead()==null).toList();int index=0;for(LeadImportRow row:validRows){Map<String,String> data=map(row.getNormalizedDataJson());User assignee=executives.get(index++%executives.size());Lead lead=new Lead();lead.setLeadName(data.get("leadName"));lead.setEmail(blankNull(data.get("email")));lead.setPhone(blankNull(data.get("phone")));lead.setGeoLocation(blankNull(data.get("geoLocation")));lead.setState(blankNull(data.get("state")));lead.setInterestedService(blankNull(data.get("interestedService")));lead.setPersonalDetails(data.get("personalDetails")==null?null:write(Map.of("value",data.get("personalDetails"))));lead.setExternalId(blankNull(data.get("externalId")));lead.setDuplicateHash(hash(data));lead.setEstimatedValue(decimal(data.get("estimatedValue")));lead.setAssignedUser(assignee);lead.setAssignedAt(LocalDateTime.now());lead.setStatus(LeadStatus.ASSIGNED);lead.setConverted(false);String source=data.get("source");if(source!=null&&!source.isBlank())sources.findBySourceNameIgnoreCase(source).ifPresent(lead::setSource);lead=leads.save(lead);row.setImportedLead(lead);LeadHistory audit=new LeadHistory();audit.setLead(lead);audit.setChangeType(LeadHistoryType.IMPORTED);audit.setNewStatus(LeadStatus.ASSIGNED);audit.setNewAssignedUser(assignee);audit.setAssignmentStrategy(LeadAssignmentStrategy.EQUAL);audit.setChangedByUser(actor);audit.setNote("Imported from "+job.getFileName()+" (row "+row.getRowNumber()+")");history.save(audit);}rows.saveAll(validRows);job.setImportedRecords(job.getImportedRecords()+validRows.size());job.setStatus(LeadImportStatus.COMPLETED);job.setCompletedAt(LocalDateTime.now());return response(imports.save(job));}

 @Transactional
 public LeadImportResponse executeWithTargets(Long id,List<Long> executiveIds,List<Long> managerIds){
  boolean managersSelected=managerIds!=null&&!managerIds.isEmpty(),executivesSelected=executiveIds!=null&&!executiveIds.isEmpty();
  if(managersSelected==executivesSelected)throw new ConflictException("ASSIGNMENT_TARGET_REQUIRED","Select either Managers or Sales Executives.");
  if(!managersSelected){LeadImportResponse result=execute(id,executiveIds);rows.findByLeadImportImportIdAndImportedLeadIsNotNullOrderByRowNumber(id).forEach(row->{Lead lead=row.getImportedLead();if(lead.getManagerOwner()==null&&lead.getAssignedUser()!=null){lead.setManagerOwner(lead.getAssignedUser().getManager());leads.save(lead);}});return result;}
  User actor=actor();
  if(actor.getRole()!=UserRole.ADMIN)throw new ForbiddenOperationException("Only Administrators can distribute imported leads to Managers.");
  LeadImport job=owned(id,actor);
  if(job.getStatus()!=LeadImportStatus.VALIDATED)throw new ConflictException("VALIDATION_REQUIRED","Validate the import before execution.");
  List<User> managers=managerIds.stream().distinct().map(uid->users.findById(uid).orElseThrow(()->new ResourceNotFoundException("A selected Manager was not found."))).toList();
  managers.forEach(this::validateManager);
  List<LeadImportRow> validRows=rows.findByLeadImportImportIdOrderByRowNumber(id).stream().filter(LeadImportRow::isValidRow).filter(r->r.getImportedLead()==null).toList();
  int index=0;
  for(LeadImportRow row:validRows){
   Map<String,String> data=map(row.getNormalizedDataJson());User manager=managers.get(index++%managers.size());Lead lead=new Lead();
   lead.setLeadName(data.get("leadName"));lead.setEmail(blankNull(data.get("email")));lead.setPhone(blankNull(data.get("phone")));lead.setGeoLocation(blankNull(data.get("geoLocation")));lead.setState(blankNull(data.get("state")));lead.setInterestedService(blankNull(data.get("interestedService")));lead.setPersonalDetails(data.get("personalDetails")==null?null:write(Map.of("value",data.get("personalDetails"))));lead.setExternalId(blankNull(data.get("externalId")));lead.setDuplicateHash(hash(data));lead.setEstimatedValue(decimal(data.get("estimatedValue")));lead.setManagerOwner(manager);lead.setStatus(LeadStatus.NEW);lead.setConverted(false);
   String source=data.get("source");if(source!=null&&!source.isBlank())sources.findBySourceNameIgnoreCase(source).ifPresent(lead::setSource);lead=leads.save(lead);row.setImportedLead(lead);
   LeadHistory audit=new LeadHistory();audit.setLead(lead);audit.setChangeType(LeadHistoryType.IMPORTED);audit.setNewStatus(LeadStatus.NEW);audit.setNewManagerOwner(manager);audit.setAssignmentStrategy(LeadAssignmentStrategy.EQUAL);audit.setChangedByUser(actor);audit.setNote("Imported from "+job.getFileName()+" (row "+row.getRowNumber()+")");history.save(audit);
  }
  rows.saveAll(validRows);job.setImportedRecords(job.getImportedRecords()+validRows.size());job.setStatus(LeadImportStatus.COMPLETED);job.setCompletedAt(LocalDateTime.now());return response(imports.save(job));
 }

 @Transactional public void delete(Long id){User actor=actor();LeadImport job=owned(id,actor);if(job.getImportedRecords()>0)throw new ConflictException("IMPORT_ALREADY_EXECUTED","Completed imports are retained for audit history.");imports.delete(job);}

 private User actor(){return users.findById(currentUserService.getCurrentUserId()).orElseThrow(()->new ResourceNotFoundException("Authenticated user was not found."));}
 private void requireImporter(User u){if(u.getRole()==UserRole.SALES_EXECUTIVE)throw new ForbiddenOperationException("Only Administrators and Managers can import leads.");}
 private LeadImport owned(Long id,User actor){requireImporter(actor);LeadImport job=imports.findDetailedByImportId(id).orElseThrow(()->new ResourceNotFoundException("Lead import was not found."));if(actor.getRole()!=UserRole.ADMIN&&!job.getUploadedBy().getUserId().equals(actor.getUserId()))throw new ResourceNotFoundException("Lead import was not found.");return job;}
 private LeadImport trackable(Long id,User actor){requireImporter(actor);LeadImport job=imports.findDetailedByImportId(id).orElseThrow(()->new ResourceNotFoundException("Lead import was not found."));if(actor.getRole()==UserRole.ADMIN||job.getUploadedBy().getUserId().equals(actor.getUserId()))return job;if(actor.getRole()==UserRole.MANAGER&&rows.existsVisibleToManager(id,actor.getUserId()))return job;throw new ResourceNotFoundException("Lead import was not found.");}
 private void ensureEditable(LeadImport j){if(j.getStatus()==LeadImportStatus.COMPLETED)throw new ConflictException("IMPORT_COMPLETED","A completed import cannot be changed.");}
 private void validateExecutive(User actor,User u){if(u.getRole()!=UserRole.SALES_EXECUTIVE||!Boolean.TRUE.equals(u.getActive())||Boolean.TRUE.equals(u.getAccountLocked()))throw new ConflictException("INVALID_ASSIGNEE","Select active, unlocked Sales Executives only.");if(actor.getRole()==UserRole.MANAGER&&(u.getManager()==null||!u.getManager().getUserId().equals(actor.getUserId())))throw new ForbiddenOperationException("Managers can assign imported leads only to their own Sales Executives.");}
 private void validateManager(User u){if(u.getRole()!=UserRole.MANAGER||!Boolean.TRUE.equals(u.getActive())||Boolean.TRUE.equals(u.getAccountLocked()))throw new ConflictException("INVALID_MANAGER","Select active, unlocked Managers only.");}
 private Map<String,String> normalize(Map<String,String> raw,Map<String,String> mapping){Map<String,String> n=new LinkedHashMap<>();mapping.forEach((field,column)->n.put(field,trim(raw.get(column))));String name=trim(n.get("leadName"));if(name.isBlank())name=(trim(n.get("firstName"))+" "+trim(n.get("lastName"))).trim();n.put("leadName",name);n.computeIfPresent("email",(k,v)->v.toLowerCase(Locale.ROOT));n.computeIfPresent("phone",(k,v)->v.replaceAll("[^0-9+]",""));return n;}
 private List<String> validateRow(Map<String,String> n){List<String> e=new ArrayList<>();if(trim(n.get("leadName")).isBlank())e.add("Lead name is required.");String email=trim(n.get("email")),phone=trim(n.get("phone"));if(email.isBlank()&&phone.isBlank())e.add("Email or phone is required.");if(!email.isBlank()&&!EMAIL.matcher(email).matches())e.add("Email address is invalid.");if(!phone.isBlank()&&phone.replaceAll("\\D","").length()<7)e.add("Phone number is invalid.");try{decimal(n.get("estimatedValue"));}catch(Exception x){e.add("Estimated value must be numeric.");}return e;}
 private boolean existingIdentity(Map<String,String> n){String email=blankNull(n.get("email")),phone=blankNull(n.get("phone"));return(email!=null&&leads.existsByEmailIgnoreCase(email))||(phone!=null&&leads.existsByPhone(phone));}
 private String hash(Map<String,String> n){String identity=!trim(n.get("email")).isBlank()?trim(n.get("email")).toLowerCase(Locale.ROOT):trim(n.get("phone"));if(identity.isBlank())return"";try{return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(identity.getBytes(StandardCharsets.UTF_8)));}catch(Exception e){throw new IllegalStateException(e);}}
 private LeadImportFileType type(String name){String ext=name==null?"":name.substring(name.lastIndexOf('.')+1).toUpperCase(Locale.ROOT);try{return LeadImportFileType.valueOf(ext);}catch(Exception e){throw new IllegalArgumentException("Supported formats are CSV, XLS, XLSX and JSON.");}}
 private String safeName(String n){String s=n==null?"leads":""+n.replace('\\','/');return s.substring(s.lastIndexOf('/')+1);}
 private String write(Object v){try{return json.writeValueAsString(v);}catch(Exception e){throw new IllegalArgumentException("Unable to process import data.");}}
 private Map<String,String> map(String v){if(v==null)return new LinkedHashMap<>();try{return json.readValue(v,new TypeReference<LinkedHashMap<String,String>>(){});}catch(Exception e){throw new IllegalArgumentException("Stored import data is invalid.");}}
 private List<String> list(String v){try{return json.readValue(v,new TypeReference<List<String>>(){});}catch(Exception e){return List.of();}}
 private String trim(String v){return v==null?"":v.trim();} private String blankNull(String v){String s=trim(v);return s.isBlank()?null:s;} private BigDecimal decimal(String v){String s=trim(v);if(s.isBlank())return BigDecimal.ZERO;String normalized=s.replace(",","").replace(" ","").replace("₹","").replace("$","").replace("€","").replace("£","");return new BigDecimal(normalized);}
 private Map<String,String> suggestions(List<String> columns){Map<String,String> out=new LinkedHashMap<>();for(String c:columns){String k=c.toLowerCase(Locale.ROOT).replaceAll("[^a-z0-9]","");if(k.matches("firstname|fname|givenname"))out.putIfAbsent("firstName",c);else if(k.matches("lastname|lname|surname"))out.putIfAbsent("lastName",c);else if(k.matches("name|leadname|fullname"))out.putIfAbsent("leadName",c);else if(k.matches("email|emailaddress"))out.putIfAbsent("email",c);else if(k.matches("phone|mobile|mobilenumber|phonenumber"))out.putIfAbsent("phone",c);else if(k.matches("source|leadsource"))out.putIfAbsent("source",c);else if(k.matches("state|province"))out.putIfAbsent("state",c);else if(k.matches("location|geolocation|city"))out.putIfAbsent("geoLocation",c);else if(k.matches("service|interestedservice"))out.putIfAbsent("interestedService",c);else if(k.matches("externalid|referenceid"))out.putIfAbsent("externalId",c);else if(k.matches("estimatedvalue|value|amount"))out.putIfAbsent("estimatedValue",c);}return out;}
 private LeadImportResponse response(LeadImport j){List<String> cols=list(j.getDetectedColumnsJson());return new LeadImportResponse(j.getImportId(),j.getFileName(),j.getFileType(),j.getStatus(),j.getUploadedBy().getUserId(),j.getUploadedBy().getFullName(),cols,map(j.getColumnMappingJson()),j.getTotalRecords(),j.getValidRecords(),j.getInvalidRecords(),j.getDuplicateRecords(),j.getImportedRecords(),j.getFailureMessage(),j.getCreatedAt(),j.getCompletedAt(),suggestions(cols));}
 private Map<LeadStatus,Long> emptyStatusCounts(){Map<LeadStatus,Long> counts=new EnumMap<>(LeadStatus.class);for(LeadStatus status:LeadStatus.values())counts.put(status,0L);return counts;}
 private Map<String,String> fieldErrors(List<String> errors){Map<String,String> result=new LinkedHashMap<>();for(String error:errors){String lower=error.toLowerCase(Locale.ROOT);if(lower.contains("lead name"))result.put("leadName",error);if(lower.contains("email"))result.put("email",error);if(lower.contains("phone"))result.put("phone",error);if(lower.contains("email or phone")){result.put("email",error);result.put("phone",error);}if(lower.contains("estimated value"))result.put("estimatedValue",error);}return result;}
 private LeadImportRowResponse rowResponse(LeadImportRow r){List<String> errors=list(r.getValidationErrorsJson());return new LeadImportRowResponse(r.getRowId(),r.getRowNumber(),map(r.getRawDataJson()),map(r.getNormalizedDataJson()),errors,fieldErrors(errors),r.isValidRow(),r.isDuplicateRow(),r.getImportedLead()==null?null:r.getImportedLead().getLeadId());}
}
