package com.example.Email.Service;
import com.example.CRM.Entity.User;import com.example.CRM.Repository.UserRepository;import com.example.Common.Exception.*;import com.example.Common.Service.CurrentUserService;import com.example.Email.DTO.Response.EmailAccountResponse;import com.example.Email.Entity.*;import com.example.Email.Repository.*;
import lombok.RequiredArgsConstructor;import org.springframework.beans.factory.annotation.Value;import org.springframework.http.MediaType;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import org.springframework.util.LinkedMultiValueMap;import org.springframework.web.client.RestClient;import org.springframework.web.util.UriComponentsBuilder;
import java.nio.charset.StandardCharsets;import java.security.*;import java.time.*;import java.util.*;
@Service @RequiredArgsConstructor @Transactional(readOnly=true)
public class EmailAccountService {
 private final EmailAccountRepository accounts;private final EmailOAuthStateRepository states;private final UserRepository users;private final CurrentUserService current;private final EmailTokenCipher cipher;private final RestClient http=RestClient.create();
 @Value("${email.oauth.google.client-id:}") private String googleId;@Value("${email.oauth.google.client-secret:}") private String googleSecret;
 @Value("${email.oauth.microsoft.client-id:}") private String microsoftId;@Value("${email.oauth.microsoft.client-secret:}") private String microsoftSecret;@Value("${email.oauth.microsoft.tenant:common}") private String tenant;
 public List<EmailAccountResponse> list(){return accounts.findByUserUserIdOrderByCreatedAtAsc(uid()).stream().map(this::response).toList();}
 @Transactional public String authorizationUrl(EmailProvider provider,String redirectUri){if(provider!=EmailProvider.GMAIL&&provider!=EmailProvider.MICROSOFT_365)throw new IllegalArgumentException("OAuth is supported for Gmail and Microsoft 365.");credentials(provider);String raw=UUID.randomUUID()+"."+UUID.randomUUID();EmailOAuthState s=new EmailOAuthState();s.setStateHash(hash(raw));s.setUserId(uid());s.setProvider(provider);s.setRedirectUri(redirectUri);s.setExpiresAt(Instant.now().plus(Duration.ofMinutes(10)));states.save(s);return provider==EmailProvider.GMAIL?UriComponentsBuilder.fromUriString("https://accounts.google.com/o/oauth2/v2/auth").queryParam("client_id",googleId).queryParam("redirect_uri",redirectUri).queryParam("response_type","code").queryParam("access_type","offline").queryParam("prompt","consent").queryParam("include_granted_scopes","true").queryParam("scope","openid email https://www.googleapis.com/auth/gmail.modify").queryParam("state",raw).build().encode().toUriString():UriComponentsBuilder.fromUriString("https://login.microsoftonline.com/"+tenant+"/oauth2/v2.0/authorize").queryParam("client_id",microsoftId).queryParam("redirect_uri",redirectUri).queryParam("response_type","code").queryParam("response_mode","query").queryParam("scope","openid profile email offline_access Mail.ReadWrite Mail.Send").queryParam("state",raw).build().encode().toUriString();}
 @Transactional public EmailAccountResponse complete(String code,String rawState){EmailOAuthState s=states.findById(hash(rawState)).orElseThrow(()->new IllegalArgumentException("Invalid OAuth state."));if(s.getExpiresAt().isBefore(Instant.now())||!s.getUserId().equals(uid()))throw new IllegalArgumentException("OAuth state expired or does not belong to this user.");Map<String,Object> token=exchange(s,code);String access=str(token,"access_token");Map<String,Object> profile=profile(s.getProvider(),access);String email=s.getProvider()==EmailProvider.GMAIL?str(profile,"emailAddress"):str(profile,"mail");if(email==null||email.isBlank())email=str(profile,"userPrincipalName");String name=s.getProvider()==EmailProvider.GMAIL?email:str(profile,"displayName");User user=users.findById(uid()).orElseThrow(()->new ResourceNotFoundException("Current user not found."));EmailAccount a=accounts.findByUserUserIdAndProviderAndEmailAddressIgnoreCase(uid(),s.getProvider(),email).orElseGet(EmailAccount::new);a.setUser(user);a.setProvider(s.getProvider());a.setEmailAddress(email.toLowerCase(Locale.ROOT));a.setDisplayName(name);a.setStatus(EmailAccountStatus.CONNECTED);a.setEncryptedAccessToken(cipher.encrypt(access));String refresh=str(token,"refresh_token");if(refresh!=null)a.setEncryptedRefreshToken(cipher.encrypt(refresh));a.setGrantedScopes(str(token,"scope"));Number expires=(Number)token.get("expires_in");if(expires!=null)a.setTokenExpiresAt(Instant.now().plusSeconds(expires.longValue()));a.setLastSyncError(null);a=accounts.save(a);states.delete(s);return response(a);}
 @Transactional public void disconnect(Long id){EmailAccount a=accounts.findByAccountIdAndUserUserId(id,uid()).orElseThrow(()->new ResourceNotFoundException("Email account not found."));a.setStatus(EmailAccountStatus.DISCONNECTED);a.setEncryptedAccessToken(null);a.setEncryptedRefreshToken(null);a.setSyncCursor(null);a.setSubscriptionId(null);}
 private Map<String,Object> exchange(EmailOAuthState s,String code){LinkedMultiValueMap<String,String> f=new LinkedMultiValueMap<>();f.add("client_id",s.getProvider()==EmailProvider.GMAIL?googleId:microsoftId);f.add("client_secret",s.getProvider()==EmailProvider.GMAIL?googleSecret:microsoftSecret);f.add("code",code);f.add("redirect_uri",s.getRedirectUri());f.add("grant_type","authorization_code");String url=s.getProvider()==EmailProvider.GMAIL?"https://oauth2.googleapis.com/token":"https://login.microsoftonline.com/"+tenant+"/oauth2/v2.0/token";return require(http.post().uri(url).contentType(MediaType.APPLICATION_FORM_URLENCODED).body(f).retrieve().body(Map.class));}
 private Map<String,Object> profile(EmailProvider p,String token){String url=p==EmailProvider.GMAIL?"https://gmail.googleapis.com/gmail/v1/users/me/profile":"https://graph.microsoft.com/v1.0/me?$select=displayName,mail,userPrincipalName";return require(http.get().uri(url).headers(h->h.setBearerAuth(token)).retrieve().body(Map.class));}
 private void credentials(EmailProvider p){if((p==EmailProvider.GMAIL&&(blank(googleId)||blank(googleSecret)))||(p==EmailProvider.MICROSOFT_365&&(blank(microsoftId)||blank(microsoftSecret))))throw new IllegalStateException("OAuth credentials are not configured for "+p+".");}
 private EmailAccountResponse response(EmailAccount a){return new EmailAccountResponse(a.getAccountId(),a.getProvider(),a.getEmailAddress(),a.getDisplayName(),a.getStatus(),a.getLastSyncAt(),a.getLastSyncError(),a.getSubscriptionExpiresAt());}
 private Long uid(){return current.getCurrentUserId();}private boolean blank(String x){return x==null||x.isBlank();}private String str(Map<String,Object> m,String k){Object v=m.get(k);return v==null?null:v.toString();}private Map<String,Object> require(Map<String,Object> m){if(m==null)throw new IllegalStateException("Provider returned an empty response.");return m;}
 private String hash(String v){try{return java.util.HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(v.getBytes(StandardCharsets.UTF_8)));}catch(NoSuchAlgorithmException e){throw new IllegalStateException(e);}}
}
