package com.example.Email.Service;
import com.example.CRM.Entity.User;import com.example.CRM.Repository.*;import com.example.Common.Exception.ResourceNotFoundException;import com.example.Common.Service.CurrentUserService;import com.example.Email.DTO.Request.LinkEmailToCrmRequest;import com.example.Email.DTO.Response.EmailCrmLinkResponse;import com.example.Email.Entity.*;import com.example.Email.Repository.*;
import lombok.RequiredArgsConstructor;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import java.time.Instant;import java.util.*;
@Service @RequiredArgsConstructor @Transactional(readOnly=true)
public class EmailCrmLinkService {
 private final EmailCrmLinkRepository links;private final EmailMailboxEntryRepository mailbox;private final ContactRepository contacts;private final LeadRepository leads;private final UserRepository users;private final CurrentUserService current;
 @Transactional public void autoLink(EmailMessage m,Collection<String> addresses){for(String email:addresses){contacts.findFirstByEmailIgnoreCase(email).ifPresent(c->create(m,"CONTACT",c.getContactId().toString(),"RECIPIENT",m.getSender()));leads.findFirstByEmailIgnoreCase(email).ifPresent(l->create(m,"LEAD",l.getLeadId().toString(),"RECIPIENT",m.getSender()));}}
 @Transactional public EmailCrmLinkResponse link(Long messageId,LinkEmailToCrmRequest r){EmailMailboxEntry e=mailbox.findDetailed(new EmailMailboxEntryId(messageId,current.getCurrentUserId())).orElseThrow(()->new ResourceNotFoundException("Email not found."));validate(r.entityType(),r.entityId());User u=users.findById(current.getCurrentUserId()).orElseThrow(()->new ResourceNotFoundException("Current user not found."));return response(create(e.getMessage(),r.entityType(),r.entityId(),r.relationshipType()==null?"RELATED":r.relationshipType(),u));}
 public List<EmailCrmLinkResponse> forEntity(String type,String id){validate(type,id);return links.findByEntityTypeAndEntityIdOrderByCreatedAtDesc(type,id).stream().map(this::response).toList();}
 private EmailCrmLink create(EmailMessage m,String type,String id,String relation,User user){if(links.existsByMessageMessageIdAndEntityTypeAndEntityIdAndRelationshipType(m.getMessageId(),type,id,relation))return links.findByEntityTypeAndEntityIdOrderByCreatedAtDesc(type,id).stream().filter(x->x.getMessage().getMessageId().equals(m.getMessageId())&&x.getRelationshipType().equals(relation)).findFirst().orElseThrow();EmailCrmLink x=new EmailCrmLink();x.setMessage(m);x.setEntityType(type);x.setEntityId(id);x.setRelationshipType(relation);x.setLinkedBy(user);x.setCreatedAt(Instant.now());return links.save(x);}
 private void validate(String type,String id){Long n;try{n=Long.valueOf(id);}catch(Exception e){throw new IllegalArgumentException("CRM entity id must be numeric.");}switch(type){case"CONTACT"->contacts.findById(n).orElseThrow(()->new ResourceNotFoundException("Contact not found."));case"LEAD"->leads.findById(n).orElseThrow(()->new ResourceNotFoundException("Lead not found."));default->{if(!Set.of("COMPANY","DEAL","CALENDAR_EVENT","CALL","TASK").contains(type))throw new IllegalArgumentException("Unsupported CRM entity type.");}}}
 private EmailCrmLinkResponse response(EmailCrmLink x){return new EmailCrmLinkResponse(x.getLinkId(),x.getMessage().getMessageId(),x.getEntityType(),x.getEntityId(),x.getRelationshipType(),x.getCreatedAt());}
}
